### ISSUE TITLE
SERVIDOR ULBRA

### ISSUE THREAD

**Issue by Lynoge** [Ulbra-Gravatai/sistemaTCC#107]
### Descrição
Ultimas modificações colocadas no servidor da Ulbra.
### Comportamento Esperado
Que não tenha bugs. 
Verificar com o Elgio sobre o acesso externo, e alguém tentar acessar internamente para achar possíveis bugs.
### Comportamento Atual
Somente testes locais, externo não esta funcionando ainda.
### Não esqueça de colocar um print com o problema
Acesso externo somente indo pela rota. E fica assim.

![image](https://cloud.githubusercontent.com/assets/1576527/20149224/7e9a19f2-a697-11e6-94fe-d12794b3474e.png)

**Comment by grschroder** [comment]
Enquanto não arrumamos esse bug, você pode acessar através da porta 8080.

http://gravatai.ulbra.tche.br:8080/sistemaTCC/aluno/listar
