### ISSUE TITLE
Não exclui professor

### ISSUE THREAD

**Issue by beped** [Ulbra-Gravatai/sistemaTCC#108]
### Descrição
Ao tentar excluir um professor, aparece a mensagem de confirmação da exclusão, porém, a mesma não acontece no banco de dados.
### Comportamento Esperado
Ao confirmar a exclusão, deveria excluir do banco de dados.
### Comportamento Atual
Não exclui o cadastro de professor.
### Passos para reprodução do Problema
Entrar no menu Professores>Selecionar o perfil que deseja excluir>clicar em Excluir> Clicar em Confirmar
### Não esqueça de colocar um print com o problema
![untitled-1](https://cloud.githubusercontent.com/assets/11295620/20137434/893786be-a661-11e6-8739-ed6f503aa32e.jpg)

**Comment by expalmer** [comment]
Entre na pasta ``config`` e execute os arquivos ``*.sql`` para atualizar tua base, então drá tudo certo!

**Comment by jeanbauer** [comment]
@expalmer Existe outros comandos que é necessário hoje para ter a aplicação rodando? Abraço o/

**Comment by expalmer** [comment]
Isso @jeanbauer \o. Executa lá os scripts.
