### ISSUE TITLE
Problema no campo de cadastro do aluno

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#113]
### Descrição
o campo está com um botão para decrementar ou aumentar
nos campos cgu e matricula, ambos estão aceitando mais números do que o esperado

### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/20867392/20182397/ce1cd27e-a748-11e6-84f0-83c66fc4f9a8.png)

**Comment by expalmer** [comment]
Conforme as tabelas, ambos os campos aceitam 10 caracteres apenas, entra no controller do alunos e muda o campo de tamanho das linhas 21 e 22.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam ou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, obviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam ou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, obviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam ou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, obviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam oou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, óbviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam ou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, obviamente.

**Comment by modernfunkboss** [comment]
Uma parte se da por causa do tipo do input. acredito estar definido no CSS para ter botões que aumentam ou diminuem o numero do CGU, troquei para texto a input, no entanto passou a aceitar texto, obviamente.
