### ISSUE TITLE
Preoblemas com o issue70.sql

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#114]
### Descrição.
Coloco para executar no phpmyadmin e trava na tela de execussão

**Comment by ThiagoMMoura** [comment]
Qual o erro que aparece?
Poderia colocar um print?

**Comment by expalmer** [comment]
Essa 70 são poucas linhas, executa uma de cada vez.
Verifica se já tem a tabela ``etapa_status`` e se tem registro nela.

**Comment by modernfunkboss** [comment]
tem a tabela mas não te registros. aí eu rodo o sql e freeza na tela de execussão
não acontece nada só isso, não da erro, nada

**Comment by modernfunkboss** [comment]
Tirei as linhas LOCK e UNLOCK e gravou o registro de boas
