### ISSUE TITLE
Botão Salvar não da submit

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#115]
### Descrição
O Botão das areas aluno cadastro e professor cadastro não estão mandando o subimit
### Comportamento Esperado
Cadastrar os dados solicitados
### Comportamento Atual
Nada
### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/20867392/20197217/6c1ab46e-a785-11e6-963d-7f6deb4f0a0c.png)

**Comment by expalmer** [comment]
Abre o DEVTOOLS do chrome, e verifica na aba ``network`` o que realmente está acontecendo. Pode ser que seja algo no teu ambiente, mas tenta verificar o motivo do erro.

**Comment by ThiagoMMoura** [comment]
![cadastrar professor ok](https://cloud.githubusercontent.com/assets/8551632/20214907/230ba756-a7f8-11e6-9ac1-2f0f1193dd66.png)
