### ISSUE TITLE
Problemas ao acessar semestre listar

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#118]
### Descrição
Aparece as mensagens a seguir

### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/20867392/20197540/44f26916-a787-11e6-8a86-d0632b8b399c.png)

**Comment by expalmer** [comment]
@everton08 acho que tu não acabou essa rotina ainda né?

**Comment by everton08** [comment]
to corrigindo uns conflitos e subindoo :D
