### ISSUE TITLE
Links do menu

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#119]
### Descrição
os links do menu não estão direcionando corretamente

### Comportamento Esperado
abrir localhost/sistemaTCC/public/<pagina desejada>

### Comportamento Atual
Substitui o public ficando
localhost/<pagina desejada>

### Não esqueça de colocar um print com o problema
Verifique o link como fica no canto inferior esquerdo da pagina

![image](https://cloud.githubusercontent.com/assets/20867392/20197943/28614c7a-a789-11e6-9816-d88346188c49.png)

**Comment by ThiagoMMoura** [comment]
Este problema já foi corrigido conforme o merge #116
