### ISSUE TITLE
Nome do Semestre Permite Somente Letras

### ISSUE THREAD

**Issue by douglasangeli** [Ulbra-Gravatai/sistemaTCC#124]
### Descrição
Ao cadastrar ou editar um semestre, só é permitido que seja atribuído a ele um nome que não contenha números. No caso de a Prof. Adelina querer colocar o nome do semestre como '2017-1', por exemplo, não seria permitido.

### Comportamento Esperado
Já que o campo de nome do semestre é alfanumérico, pode ser permitido qualquer valor.

### Comportamento Atual
Não permite nomes que contenham caracteres numéricos.

### Passos para reprodução do Problema
Incluir ou alterar um semestre e tentar salvá-lo com um caractere numérico no campo de nome.

### Print com o problema
![screencapture-localhost-9999-semestre-editar-1-1478877590712](https://cloud.githubusercontent.com/assets/14776862/20219824/3c3c06e8-a812-11e6-8105-cdf805cfc882.png)

**Comment by selatotal** [comment]
Duplicate #128
