### ISSUE TITLE
Mensagens de validação em Criar/Editar Aluno

### ISSUE THREAD

**Issue by ericquadros** [Ulbra-Gravatai/sistemaTCC#127]
### Descrição
As mensagens de validação nas telas criar e editar aluno nos campos CGU e Matrícula está exibindo em inglês

### Comportamento Esperado
Espera-se que as mensagens sejam exibidas em português

### Comportamento Atual
Está exibindo em inglês as mensagens de validação dos campos CGU e Matrícula

### Passos para reprodução do Problema
Alterar as mensagens de validação para português

### Não esqueça de colocar um print com o problema
![validacao-aluno](https://cloud.githubusercontent.com/assets/11640701/20231021/1c5de1dc-a846-11e6-8a99-db1906189b1b.png)

**Comment by ThiagoMMoura** [comment]
Este problema já foi relatado e corrigido pela Issue #122
