### ISSUE TITLE
Validação em Criar/Editar Semestre 

### ISSUE THREAD

**Issue by ericquadros** [Ulbra-Gravatai/sistemaTCC#128]
### Descrição
A validação do nome do semestre não está permitindo somente números 

### Comportamento Esperado
Espera-se que permita números, como 1, 2016/01, 2016/1

### Comportamento Atual
Não permite salvar números

### Passos para reprodução do Problema
Permitir que salve apenas números também

### Não esqueça de colocar um print com o problema
![validacao-semestre](https://cloud.githubusercontent.com/assets/11640701/20231513/98cec8c8-a849-11e6-9c62-cefb0b2a7c35.png)

**Comment by everton08** [comment]
@ericquadros vou dar uma olhada nesse bug!!!

**Comment by faelborba** [comment]
Feito, Aceitando qualquer tipo de dados no momento. Valeu.
