### ISSUE TITLE
Não renderiza?

### ISSUE THREAD

**Issue by ThiagoLencina** [Ulbra-Gravatai/sistemaTCC#13]
![image](https://cloud.githubusercontent.com/assets/21270271/19023074/e5104c0a-88bb-11e6-8d89-e007f75b0776.png)

Alguma ideia do que pode estar faltando?

**Comment by edersoares** [comment]
Acessar a URL .../public/professor/cadastrar/

**Comment by selatotal** [comment]
Erro de usuário, conforme o Thago comentou no Slack
