### ISSUE TITLE
Login - Não funciona

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#131]
### Descrição
Login não funciona a menos que o usuário saiba o link de uma das funcionalidades

### Comportamento Esperado
Ao usuário entrar na página inicial, após digitar usuário e senha, deve exibir a tela do sistema

### Comportamento Atual
Fica em loop na página de login

### Passos para reprodução do Problema
- Acessar o index
- Informar usuário e senha válido

**Comment by beped** [comment]
Olá, esta como Closed, porém não foi corrigido isso.

**Comment by selatotal** [comment]
Ainda não tem a página inicial do sistema
