### ISSUE TITLE
Semestre - Link errado para a edição na tela de listagem

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#135]
### Descrição
Na tela de listagem de semestre, ao clicar no link para edição, está direcionando para link incorreto e gerando Not-Found

### Comportamento Esperado
Deve abrir a página para edição do semestre

### Comportamento Atual
Not-Found ao clicar no link, que está direcionando para /semestre/editar/1 ao invés de /sistemaTCC/semestre/editar/1

### Passos para reprodução do Problema
- Cadastrar um semestre
- Retornar para a página de listagem
- Clicar no link de editar

**Comment by faelborba** [comment]
Feito, funcionando perfeiamente bem no momento.
