### ISSUE TITLE
Semestre - Script para Tipo de Etapa

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#137]
### Descrição
Não está no github o script para inclusão dos tipos de etapas na base de dados

### Comportamento Esperado
Todas as modificações em banco devem possuir um script no diretório /config

### Comportamento Atual
Combo de Tipo de Etapa está em branco, não sendo possível cadastrar a etapa

**Comment by edersoares** [comment]
Carregar o arquivo `config/issue137.sql` para alteração do banco de dados e registros iniciais da tabela `etapa_tipo`.
