### ISSUE TITLE
Semestre - Erro na validação de Datas

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#138]
### Descrição
Está sendo possível cadastrar um semestre com a data final anterior à data inicial

### Comportamento Esperado
A data inicial deve ser anterior a data final

### Comportamento Atual
Está sendo possível cadastrar um semestre com a data final anterior à data inicial

### Passos para reprodução do Problema
- Acessar cadastro de semestre
- Cadastrar um novo semestre
- Informar os campos obrigatórios e colocar a data final com um valor anterior à data inicial

### Não esqueça de colocar um print com o problema
![captura de tela 2016-11-11 as 21 07 36](https://cloud.githubusercontent.com/assets/178324/20232931/e98a2830-a852-11e6-994e-5ce87aeea29b.png)

**Comment by faelborba** [comment]
Feito, agora é possível cadastrar apenas semestres com data inicial superior a final, acredito que deveria ser colocado uma diferença de 6 meses no máximo para evitar um semestre cadastrado o ano odo, mas acho que isso ficaria como melhoramento.
