### ISSUE TITLE
Etapas - Permite a inclusão de apenas letras no nome das etapas

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#139]
### Descrição
Etapas está permitindo a inclusão apenas de letras no campo de nome

### Comportamento Esperado
Deve possibilitar espaços, números e barra também

### Comportamento Atual
Aceitando apenas letras

### Passos para reprodução do Problema
- Acessar o Cadastro de Semestre e incluir uma etapa
- Tentar informar o nome de etapa com letras

### Não esqueça de colocar um print com o problema
![captura de tela 2016-11-11 as 21 09 43](https://cloud.githubusercontent.com/assets/178324/20232976/34c52408-a853-11e6-9771-40423e72f57e.png)

**Comment by faelborba** [comment]
Espaço e número bombando, falta permitir caractere barra.

**Comment by faelborba** [comment]
A Mensagem está em português, mas o vazio Poderia ser tratado diferente, com a mensagem padrão 
"Preencha esse campo".
