### ISSUE TITLE
Etapas - Mensagens de Validação Incorretas

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#140]
### Descrição
As mensagens de validação de campos no cadastro de etapas dentro do semestre estão incorretas
Exemplo: Mensagem "não é um numeric válido nos campos de numero" - Alterar para colocar em português

### Comportamento Esperado
Colocar mensagem no mesmo padrão das demais telas, em um único idioma

### Comportamento Atual
- Mensagem "não é um numeric válido nos campos de numero"

### Passos para reprodução do Problema
Cadastrar um semestre dentro da etapa e clicar em Salvar deixando os campos em branco

### Não esqueça de colocar um print com o problema
![captura de tela 2016-11-11 as 21 09 43](https://cloud.githubusercontent.com/assets/178324/20233008/8a86c054-a853-11e6-9fdd-7535c8c8fb6c.png)

**Comment by faelborba** [comment]
A Mensagem está em português, mas quando o user deixar vazio Poderia ser tratado diferente, com a mensagem padrão 
"Preencha esse campo".
