### ISSUE TITLE
Semestre - Está permitindo cadastrar semestre com mesmo nome

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#145]
### Descrição
Está sendo possível cadastrar um semestre com o mesmo nome de um já cadastrado

### Comportamento Esperado
Caso tente cadastrar um semestre com o mesmo nome de um já cadastrado, deve ser informada uma mensagem com esta informação e não permitir o cadastro

### Comportamento Atual
Está sendo possível cadastrar semestre com o mesmo nome

### Passos para reprodução do Problema
- Acessar o cadastro de semestre
- Tentar cadastrar um semestre com o mesmo nome de um já cadastrado

**Comment by ThiagoMMoura** [comment]
Reabrindo Issue pois problema ainda persiste devido uma alteração no campo Nome que só permite escolher entre duas opções inalteráveis.
![nome repetido - cadastro semestre](https://cloud.githubusercontent.com/assets/8551632/20752670/9a495390-b6e9-11e6-8c16-1424b0be26bf.png)

**Comment by expalmer** [comment]
Olha só, mudaram a rotina, na real a validação sempre é por default __primeiro__ e __segundo__, mas qual será o critério para mostrar que um semestre é diferente de outro ?

**Comment by ThiagoMMoura** [comment]
Poderia conter o ano no nome como no modelo ANO/SEMESTRE, exemplos: 2017/1, 2017/2

**Comment by expalmer** [comment]
Concordo

**Comment by faelborba** [comment]
Concordo, Douglas está vendo isso.
