### ISSUE TITLE
Dificuldade de acesso - erro 500

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#148]
### Descrição
Ao tentar a cessar a aplicação, tela fica em branco, em insepcionar elemento, network aparece erro 500
### Comportamento Esperado
deveria aparecer a tela inicial do sistema.
### Comportamento Atual
Tela em branco.
Em inspecionar elemento aparece erro 500.
No terminal apresenta 127.0.0.1:49246 [500]: / - Class 'Symfony\Component\Security\Http\Firewall' not found in /var/www/html/sistemaTCC/vendor/silex/silex/src/Silex/Provider/SecurityServiceProvider.php on line 154
### Passos para reprodução do Problema
Dar um pull no seu local, com os dados de conexão corretos e levantando um server php, tente executar a pagina no navegador.

**Comment by expalmer** [comment]
Chama o composer de novo, pois tem uma dependência que foi adicionada.

**Comment by edersoares** [comment]
Na raiz do projeto execute `composer update`

**Comment by faelborba** [comment]
Feito, er só dar o update conforme Eder informou, eu tinha apenas tentado instalar novamente. Valeu!
