### ISSUE TITLE
Não redireciona para lugar nenhum ao logar

### ISSUE THREAD

**Issue by beped** [Ulbra-Gravatai/sistemaTCC#150]
### Descrição
Ao logar, não redireciona para página nenhuma, o usuário tem que colocar direto no link www.pagina.com.br/{local-para-onde-quer-ir}

### Comportamento Esperado
Ao efetuar o login deveria redirecionar para uma das páginas, de preferência uma home com as opçoes para o usuário escolher.
### Comportamento Atual
Não redireciona para nenhuma página ao logar.

### Passos para reprodução do Problema
Preencher usuário e senha na tela de login e clicar em Login.
![erro4](https://cloud.githubusercontent.com/assets/11295620/20402290/3eb623ec-ace3-11e6-8aee-4576fd9fb489.jpg)

**Comment by selatotal** [comment]
Duplicate #131
