### ISSUE TITLE
Descrições e Formatos de Datas.

### ISSUE THREAD

**Issue by juniorulbra** [Ulbra-Gravatai/sistemaTCC#157]
### Descrição
O sistema está apresentando e gravando a data e formato inglês.

### Comportamento Esperado
Deveria apresentar todas as datas em Português. 

### Comportamento Atual
Datas são apresentadas em formato Inglês.

### Passos para reprodução do Problema
Acesse qualquer cadastro de semestre e inclua uma data, verifique que a data é apresentada em inglês.

### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/21270261/20449062/4899c7e2-adce-11e6-938e-c005163ede8a.png)

**Comment by faelborba** [comment]
Feito, Dificuldade corrigida.
