### ISSUE TITLE
Menu / cadastrar TCC

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#159]
### Descrição
Na tela de cadas trar TCC ao clicar para expandir o menu, somos jogados na tela de login.
### Comportamento Esperado
Apenas mostrar o menu de opções.
### Comportamento Atual
Jogando para tela inicial
### Passos para reprodução do Problema
Acesse o sistema, selecione a opção cadastrar TCC, agora ente chamar o menu, você será jogado na tela de login.

**Comment by expalmer** [comment]
Não procede pra mim. Confirma para fecharmos essa issue!
