### ISSUE TITLE
Tela para cadastrar área de interesse do professor

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#160]
### Descrição
Falta tela para cadastrar área de interesse do professor, atualmente esse cadastro somente é possível através do banco de dados. Isso dificulta o cadastro de professores, pois o mesmo exige que tenha que ter ao menos uma área de interesse selecionada.
### Comportamento Esperado
Existir a tela, se possível um botão dentro da tela de cadastro de professor que direciona para tela de cadastrar mais áreas de interesse.
### Comportamento Atual
Não gtem como cadastrar se não for diretamente no banco e inserir as área de interesse manualmente.
### Passos para reprodução do Problema
Acessar a tela de cadastro de professor.

**Comment by expalmer** [comment]
Faremos isso
