### ISSUE TITLE
Tela listar professor falta área de interesse

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#161]
### Descrição
Na tela de listar professores falta o campo de áreas de interesse, Não sei como poderia ser a exibição, afinal podem ser mais de uma área de interesse, não sei se seria interessante tela ali, essa issue é mais para questionar se é ou não viável tal adição
### Comportamento Esperado
Ter uma forma de exibir as áreas de interesse do professor
### Comportamento Atual
Não tem.
### Passos para reprodução do Problema
acessar página de listar professor

**Comment by expalmer** [comment]
Essa rotina já está pronto, apenas crie as áreas de interesse no banco.
Depois confirma se deu tudo certo para fechar essa issue.
