### ISSUE TITLE
Campo de seleção de aluno ao Cadastrar TCC deveria ser campo de pesquisa

### ISSUE THREAD

**Issue by beped** [Ulbra-Gravatai/sistemaTCC#164]
### Descrição
Na tela de cadastro de TCC's tem uma caixa de seleção dos alunos, porém, quando estiver com vários alunos cadastrados vai ser um saco ficar catando ali no meio o nome do mesmo. Sem contar que pode ter aluno com o mesmo nome, visto que a ideia do projeto é usar em outros campus também.
### Comportamento Esperado
Deveria ter um campo de pesquisa pra retornar somente o(os) nomes procurados no formato { Nome do aluno - CGU } ou no mínimo a caixa de seleção ao invés de aparecer somente o nome do aluno deveria aparecer  { Nome do aluno - CGU }.
### Comportamento Atual
Lista de nomes para a seleção do aluno.
### Passos para reprodução do Problema
Entrar em Cadastrar TCC
![erro7](https://cloud.githubusercontent.com/assets/11295620/20596542/2dbab5ec-b226-11e6-979f-3d0dfedc36f2.jpg)

**Comment by ericquadros** [comment]
Estou fazendo essa! Deixa pra mim! Valeu
