### ISSUE TITLE
Cadastrar campus permitindo nome do campus contendo apenas números

### ISSUE THREAD

**Issue by diogo-machado** [Ulbra-Gravatai/sistemaTCC#173]
### Descrição
Cadastrar campus permite o cadastro de campus contendo apenas números como nome.

### Comportamento Esperado
Não permitir o cadastro com **apenas** números no nome.

### Comportamento Atual
Permitir o cadastro de campus contendo apenas números.

### Passos para reprodução do Problema
Cadastrar novo campus colocando apenas números como nome.
### Não esqueça de colocar um print com o problema
![i01](https://cloud.githubusercontent.com/assets/14007111/20631911/35404b5e-b318-11e6-9d61-07d36f9ffe86.png)
![i02](https://cloud.githubusercontent.com/assets/14007111/20631912/39824c3a-b318-11e6-9bc6-d3c1ec864f52.png)

**Comment by selatotal** [comment]
Não tem problema cadastrar um campus apenas com números
