### ISSUE TITLE
Editar/Cadastrar Semestre - Erro ao clicar em Cadastrar após exibir a etapa

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#179]
### Descrição
Após cadastrar o semestre e entrar na tela de etapas, o sistema permite cadastrar uma etapa corretamente mas, ao clicar no botão Cadastrar após o cadastro da Etapa, o sistema está dando erro.

### Comportamento Esperado
Ao clicar em Cadastrar, o sistema deve salvar as informações e voltar para a listagem de semestre

### Comportamento Atual
Ao clicar em Cadastrar, o sistema exibe erro.

### Passos para reprodução do Problema
- Cadastrar/Editar um Semestre com Etapa
- Clicar no botão Cadastrar

Ao verificar o retorno, notei que ele está retornando o HTML anexo. Talvez ajude na resolução

![captura de tela 2016-11-25 as 20 13 19](https://cloud.githubusercontent.com/assets/178324/20635932/b0fba8a0-b34b-11e6-9d99-0c215b440c5e.png)

[erro_semestre.txt](https://github.com/Ulbra-Gravatai/sistemaTCC/files/613927/erro_semestre.txt)

**Comment by ThiagoMMoura** [comment]
O mesmo erro ocorre na Issue #183 que já foi corrigida com o pull request #201
