### ISSUE TITLE
Cadastrar TCC - Valores e labels dos Campos

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#180]
### Descrição
Os valores e labels dos campos do cadastro de TCC estão ruins. Devem seguir o padrão das demais telas.

### Comportamento Esperado
- Ao cadastrar um novo TCC< o campo Aluno deve iniciar com um "Selecione" ao invés de aparecer um aluno 
- Listagem de alunos deve ficar em ordem alfabética
- Campo de tipo de TCC deve ter a label "Disciplina" e os valores TCC1 e TCC2 ao invés de primeiro e segundo

### Comportamento Atual
Tela abaixo:
![captura de tela 2016-11-25 as 20 18 38](https://cloud.githubusercontent.com/assets/178324/20636025/e1b96b2a-b34c-11e6-8e94-6e8ce3f98080.png)

**Comment by ericquadros** [comment]
Estou colocando um autocomplete neste campo, mas se achar melhor, deixamos
assim, apenas com um selecione...

**Comment by selatotal** [comment]
Coloca como AutoComplete
