### ISSUE TITLE
Cadastrar Aluno - Alterar o valor default do campo Sexo

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#181]
### Descrição
Devido à natureza dos cursos de Computação, deixar o valor default do campo sexo como M ao invés de F na tela de cadastro de Alunos

### Comportamento Esperado
- Valor default do campo deve ser M

### Comportamento Atual
- Valor default do campo está como F

### Passos para reprodução do Problema
- Entrar na tela de cadastrar um novo aluno

![captura de tela 2016-11-25 as 20 25 38](https://cloud.githubusercontent.com/assets/178324/20636069/5b597f56-b34d-11e6-8245-e4155478de34.png)

**Comment by ricardsosm** [comment]
corrigido
