### ISSUE TITLE
Cadastrar Professor - Alterar o valor default do campo Sexo

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#182]
### Descrição

Devido à natureza dos cursos de Computação, deixar o valor default do campo sexo como M ao invés de F na tela de cadastro de Professores

### Comportamento Esperado
- Valor default do campo deve ser M

### Comportamento Atual
- Valor default do campo está como F

### Passos para reprodução do Problema
- Acessar a tela de cadastro de professor

### Não esqueça de colocar um print com o problema
![captura de tela 2016-11-25 as 20 28 57](https://cloud.githubusercontent.com/assets/178324/20636092/d20cc7e8-b34d-11e6-94bf-20faeeae5a21.png)

**Comment by ricardsosm** [comment]
corrigido
