### ISSUE TITLE
Menu Cadastro de TCC

### ISSUE THREAD

**Issue by juniorulbra** [Ulbra-Gravatai/sistemaTCC#187]
### Descrição
Erro na descrição do menu de Cadastro de TCC está incorreto.

### Comportamento Esperado
Apresentar o nome correto

### Comportamento Atual
Nome do menu está como:
Cadastrar TTC.
### Passos para reprodução do Problema
Acesse o menu lateral e verifique o nome do menu.
### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/21270261/20636442/23dbfd90-b354-11e6-9f6d-96f892f2bf24.png)

**Comment by ricardsosm** [comment]
resolvido
