### ISSUE TITLE
Problema na exclusão  no aluno

### ISSUE THREAD

**Issue by evertonficner** [Ulbra-Gravatai/sistemaTCC#204]
### Descrição
O aluno que esta vinculado ao tcc não esta excluindo e nem apresentando mensagem de  erro
### Comportamento Atual
Ao  tentar excluir um aluno vinculado em tcc  não  esta apresentando uma mensagem  de erro
### Não esqueça de colocar um print com o problema
![aluno](https://cloud.githubusercontent.com/assets/23155027/20736477/ed94b456-b68d-11e6-906b-068c617a08ac.png)

**Comment by everton08** [comment]
qual é o comportamento esperado @evertonficner ? excluir o tcc vinculado ? informar que o aluno contém um tcc ?

**Comment by expalmer** [comment]
Não sou muito prendado em exceções, portanto fiz apenas mostrar umas mensagens. Caso tenho uma ideia melhor, avise.
@everton08 acho que não pode excluir, se tem vínculo!
