### ISSUE TITLE
Sistema deixa cadastrar alunos com mesmo CGU

### ISSUE THREAD

**Issue by beped** [Ulbra-Gravatai/sistemaTCC#208]
### Descrição
O sistema permite cadastrar alunos com o mesmo CGU
### Comportamento Esperado
Cada usuário possui o seu CGU
### Comportamento Atual
Cadastrando duplicado( mesmo CGU pra mais de 1 aluno)
### Passos para reprodução do Problema
Clicar em Aluno>Cadastrar Aluno.
![erro8](https://cloud.githubusercontent.com/assets/11295620/20833769/87a7daf0-b878-11e6-804c-2bdfd89007d1.jpg)

**Comment by diogo-machado** [comment]
Acho que este problema já foi resolvido não?

![issue](https://cloud.githubusercontent.com/assets/14007111/20834212/d753298e-b872-11e6-9316-ca813e97cf78.png)

**Comment by douglasangeli** [comment]
Foi resolvido na issue #202
