### ISSUE TITLE
Cabeçalho - Ao clicar no texto "Sistema TCC" está voltando para o formulário de login

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#220]
### Descrição
Após estar logado e clicar no link "Sistema TCC" em qualquer uma das páginas do site, o sistema está abrindo a página de login (apesar do usuário continuar logado)

### Comportamento Esperado
Ao clicar no link, o sistema deve ir para a página inicial do site

### Passos para reprodução do Problema
- Acessar qualquer página do sistema
- Clicar no texto "Sistema TCC" do cabeçalho

**Comment by ricardsosm** [comment]
corrigido
