### ISSUE TITLE
Exclusão de professor

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#24]
Ao Excluir um professor cadastrado os dados do banco de dados referente ao mesmo na tabela do BD pessoa permanecem, mas na tabela professor são escluídos. Favor corrigir para que seja excluído os dados de ambas as tabelas.

**Comment by edersoares** [comment]
@faelborba foi corrigido a exclusão da Pessoa ao excluir um Professor no pull request #26.

**Comment by edersoares** [comment]
@faelborba fui baixar tua branch porém você comitou a pasta /vendor/, favor remover e fazer novo commit. Obrigado.

**Comment by faelborba** [comment]
Ok, tudo correto e funcionando.
