### ISSUE TITLE
Adicionar ao README.md uma sessão de 'Como instalar' e 'Como executar o app'

### ISSUE THREAD

**Issue by jeanbauer** [Ulbra-Gravatai/sistemaTCC#3]
:soon:

**Comment by selatotal** [comment]
Colocar no Readme a configuração ou colocar o link para o local onde a documentação está.
Jamais fechar um issue sem colocar comentário sobre o fechamento

**Comment by edersoares** [comment]
@jeanbauer conseguiu executar a aplicação?

**Comment by jeanbauer** [comment]
Perfeito Eder!
