### ISSUE TITLE
Botão Cadastrar do Tela Listar Professores

### ISSUE THREAD

**Issue by ThiagoMMoura** [Ulbra-Gravatai/sistemaTCC#32]
### Está redirecionando para http://192.168.100.10/professor/cadastrar
![notfound](https://cloud.githubusercontent.com/assets/8551632/19614824/929b6740-97d7-11e6-8908-1e85641622ea.png)

### Para executar o problema carregue a página http://gravatai.ulbra.tche.br/sistemaTCC/professor/listar/ e clique no botão "Cadastrar Novo"
![professorlistar](https://cloud.githubusercontent.com/assets/8551632/19614877/ff094140-97d7-11e6-9ad3-9f2a74b70e8e.png)

**Comment by selatotal** [comment]
Problema no redirecionamento do servidor. Já foi resolvido.
