### ISSUE TITLE
Professor: áreas de interesse.

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#39]
### Descrição

Fatou áreas de interesse no cadastro do professor
### Comportamento Esperado

Checkbox com várias áreas de TI, onde seleciona-se com um checkbox.
### Comportamento Atual

Não existe, Nem no banco de dados.
### Passos para reprodução do Problema

Acessar o cadastro de professor no endereço ../professor/cadastrar

**Comment by expalmer** [comment]
Desculpe, mas não sei onde verificar como funciona esse processo, alguém pode me auxiliar? @ericquadros, @juniorulbra, @everton08 ?

**Comment by edersoares** [comment]
@expalmer desculpe, acabei esquecendo disso aqui, vou desenvolver a parte da base e do back.

**Comment by expalmer** [comment]
@edersoares consegue ver para nós como é esse caso ?

**Comment by juniorulbra** [comment]
Se Precisar de Ajuda, estou a disposição.

**Comment by ericquadros** [comment]
Eu também posso ajudar nesta parte, eu e o Augusto podemos ver então...

**Comment by edersoares** [comment]
Feito! Não esquecer de atualizar o banco de dados.
