### ISSUE TITLE
Responsividade

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#40]
### Descrição

Falta responsividade nas telas de listar e cadastrar professor.
### Comportamento Esperado

Como se trata de uma tabela acredito que deveria exibir os dados completos, o que não ocorre
### Comportamento Atual

É diminuido o tamanho das colunas até não aparecerem mais alguns dados, e eles não cabem nas células
### Passos para reprodução do Problema

Basta diminuir o seu navegador com uma das telas abertas.
### Não esqueça de colocar um print com o problema.

Prints:
https://www.dropbox.com/s/y181kgwtvtfwrru/Captura%20de%20tela%20de%202016-10-24%2021-50-53.png?dl=0
https://www.dropbox.com/s/vikm3pgm2zdz8yz/Captura%20de%20tela%20de%202016-10-24%2021-50-46.png?dl=0

**Comment by expalmer** [comment]
Poderia trocar o nome dessa Issue para algo mais genérico, pois na real todas as telas de cadastros não estão responsivas.

**Comment by faelborba** [comment]
Feito.

**Comment by expalmer** [comment]
Vamos deixar pra proxima
