### ISSUE TITLE
Em Cadastrar Semestre os dados do formulário não são os mesmo esperados pela API

### ISSUE THREAD

**Issue by expalmer** [Ulbra-Gravatai/sistemaTCC#46]
### Descrição

Há uma divergência nesse formulário, pois os campos enviados não são os campos que a API está esperando.

Está sendo enviado `campus, ano, semestre`, mas a API está esperando `campus dataFim dataInicio nome tipo`
### Passos para reprodução do Problema

Entrar no formulário `semestre/cadastrar/`, dar submit e abra o DEV TOOL do teu browser e veja na aba NETWORK os header e a resposta.

**Comment by ThiagoMMoura** [comment]
Divergência corrigida
