### ISSUE TITLE
AlunoController.php ocorre erro de declaração de dependência do Assert Validator

### ISSUE THREAD

**Issue by expalmer** [Ulbra-Gravatai/sistemaTCC#47]
### Descrição

Ocorre erro na parte de CRUD de alunos.

### Passos para reprodução do Problema
Use algum simulador de API como o [POSTMAN](https://www.getpostman.com/docs/introduction), e envie um POST para ``aluno/``...e ocorrerá o erro ..
```php
Fatal error: Uncaught Error: Class 'SistemaTCC\Controller\Assert\NotBlank' not found in 
```

### Solução
Informe o uso da dependência bem abaixo [desta linha](https://github.com/Ulbra-Gravatai/sistemaTCC/blob/master/src/SistemaTCC/Controller/AlunoController.php#L7).

```php
use Symfony\Component\Validator\Constraints as Assert;
```

**Comment by selatotal** [comment]
Mais fácil resolver do que reportar o problema! ;-)
