### ISSUE TITLE
Validação de usuario na autenticação

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#49]
### Descrição
Não ha validação do usuario

### Comportamento Esperado
necessária alguma autenticação std pra teste da DEV
Precisa tratar apenas a entrada de numeros no CGU para não ter problema na aplicação
Tratar as senhas

### Comportamento Atual
Apenas manda o post mas não retorna nada

### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/20867392/19686723/3d8deabc-9aa1-11e6-962d-a27f88d2d131.png)

**Comment by selatotal** [comment]
Não é um bug e sim backlog não implementado
