### ISSUE TITLE
Problemas no campo telefone do /professor

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#51]
### Descrição
Está passando texto

### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/20867392/19687776/9b51c7c8-9aa5-11e6-9859-b931e1355cb4.png)

![image](https://cloud.githubusercontent.com/assets/20867392/19687781/9f1f32aa-9aa5-11e6-8181-3297ff437e47.png)

**Comment by expalmer** [comment]
@modernfunkboss cara, atualiza teus arquivos do git pois algumas coisas já foram resolvidas.
Essa issue já foi aberta #25.
