### ISSUE TITLE
Problemas ao entrar em /semestre

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#52]
### Não esqueça de colocar um print com o problema
![image](https://cloud.githubusercontent.com/assets/20867392/19687954/59184e9e-9aa6-11e6-84c4-9fdaf2b6e2ed.png)

**Comment by jeanbauer** [comment]
Estou olhando isso

**Comment by edersoares** [comment]
@modernfunkboss ainda há o problema, acessei na master aqui e está retornando 'Index Semestre', relate se continuar havendo o problema por favor.
