### ISSUE TITLE
[DUVIDA] POR QUE O CADASTRO DO PROFESSOR CADASTRA NA TABELA PESSOA

### ISSUE THREAD

**Issue by modernfunkboss** [Ulbra-Gravatai/sistemaTCC#53]
### Descrição
POR QUE O CADASTRO DO PROFESSOR CADASTRA NA TABELA PESSOA E ONDE QUE SE FAZ A LIGAÇÃO COM O PROFESSOR?

**Comment by expalmer** [comment]
Olha a documentação [AQUI](sistemaTCC/doc/analysis/Modelagem/Modelagem.pdf)
