### ISSUE TITLE
Menu: arrastando conteúdo

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#57]
### Descrição

Ao clicar para exibir o conteúdo do menu ele arrasta o do site para direita e após quando clica para fechar, volta ao estado original.
### Comportamento Esperado

O conteúdo deveria permanecer no mesmo lugar quando se abre os menus. 
### Comportamento Atual

Está arrastando o conteúdo da tela para direita.
### Passos para reprodução do Problema

Clicar para exibir ou fechar o menu.
### Não esqueça de colocar um print com o problema

https://www.dropbox.com/s/x9kq3421rvcn078/Captura%20de%20tela%20de%202016-10-25%2021-00-22.png?dl=0

https://www.dropbox.com/s/qls5ipfl9fu909n/Captura%20de%20tela%20de%202016-10-25%2021-00-32.png?dl=0

**Comment by expalmer** [comment]
Cara eu acho que esse comportamento era o esperado quando fizeram o layout.

**Comment by ericquadros** [comment]
Também acredito que foi o esperado quando criaram...

**Comment by selatotal** [comment]
Deixamos registrado como melhoria. Se tivermos tempo resolvemos no final este problema.

**Comment by faelborba** [comment]
Se era um comportamento e esperado desulpem, é que tipoo menu ele anda suave, e a tela central simplesmente se desloca instantaneamnte para o lado.

**Comment by faelborba** [comment]
Opa, A nova funcionalidade ficou foda. Valeu
