### ISSUE TITLE
Cadastrar Professor: Nomes grandes

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#58]
### Descrição
Ao cadastrar um professor com um nome muito grande
### Comportamento Esperado
Retornar um erro ou aceitar o nome grande.
### Comportamento Atual
Nada, gera um 400 na página 400 no terminal
### Passos para reprodução do Problema
basta preencher os dados do professor e no nome colocar um nome com mais de 25 caracteres.
### Não esqueça de colocar um print com o problema
https://www.dropbox.com/s/ae6u6ofcg5c41zf/Captura%20de%20tela%20de%202016-10-25%2021-13-14.png?dl=0

**Comment by expalmer** [comment]
Sugiro aumentar o tamanho do campo na tabela pessoa.

**Comment by selatotal** [comment]
Aumentar o tamanho do campo nome para 255 e validar no Front e Backend o tamanho do campo

**Comment by edersoares** [comment]
PR #62: será necessário atualizar o banco de dados.
