### ISSUE TITLE
Erro na validação dos formulários no back-end

### ISSUE THREAD

**Issue by ThiagoMMoura** [Ulbra-Gravatai/sistemaTCC#68]
### Descrição
Ao tentar cadastrar um novo aluno, professor, semestre... (qualquer formulário que tenha validação), ocorre o seguinte erro:
`<b>Fatal error</b>:  Class 'Symfony\Component\Validator\Constraints\NotBlank' not found in <b>C:\xampp\htdocs\sistemaTCC\src\SistemaTCC\Controller\SemestreController.php</b> on line <b>17</b><br />`
### Comportamento Esperado
Exibir o alerta de confirmação e se confirma exibir o alerta de sucesso ou erro.
### Comportamento Atual
Nada acontece.
### Passos para reprodução do Problema
Abrir um formulário de cadastro que tenha validação já implementada, preencher os campos, e clicar no botão de salvar, tenha um debug aberto para verificar a resposta do servidor.
![cadastrar professor - salvar](https://cloud.githubusercontent.com/assets/8551632/19807086/358591cc-9cfd-11e6-9820-db3c9897200c.png)

**Comment by expalmer** [comment]
Você atualizou o teu master ?

**Comment by ThiagoMMoura** [comment]
Sim @expalmer , meu master está atualizado de acordo com o pull request #80 e o problema persiste.

**Comment by edersoares** [comment]
@ThiagoMMoura dê um `composer update` na raiz do projeto para atualizar as tuas dependências.

**Comment by ThiagoMMoura** [comment]
`composer update` resolveu o problema, obrigado @expalmer e @edersoares.
