### ISSUE TITLE
Cadastro de Aluno - Telas possuem posições diferentes de campos

### ISSUE THREAD

**Issue by selatotal** [Ulbra-Gravatai/sistemaTCC#77]
### Descrição

As telas de cadastro e edição de alunos não possuem os campos nas mesmas posições

### Comportamento Esperado

As duas funcionalidades devem exibir os campos nas mesmas posições em ambas as telas

### Comportamento Atual

Os campos estão em ordem diferente

### Passos para reprodução do Problema

Acessar o cadastro de alunos e a tela de edição, verá que os campos estão em ordem diferente

**Comment by ThiagoMMoura** [comment]
Sugestão: Usar a mesma view para as duas funções.
