### ISSUE TITLE
Campo telefone em cadastrar professor e aluno apaga quando não preenchido corretamente

### ISSUE THREAD

**Issue by julianivn** [Ulbra-Gravatai/sistemaTCC#90]
### Descrição
Se o usuário não preenche o telefone completo e ao trocar de campo os dados do telefone somem

### Comportamento Esperado
Os dados deveriam permanecer

### Passos para reprodução do Problema
Preencha no campo telefone um número incompleto e troque de campo, você irá perceber que o valor some. Isso acontece também quando preenchemos o valor e damos um submit

![bug_](https://cloud.githubusercontent.com/assets/22016707/19953577/a5b66e5a-a156-11e6-9031-ddf7542a9cc4.PNG)

**Comment by ThiagoMMoura** [comment]
Conforme solicitado na Issue #75 foi adicionado uma mascará para o campo telefone, que formata o campo e valida somente a quantidade de dígitos permitida. A API utilizada para criar a mascará limpa o campo caso o valor não corresponda ao esperado fazendo então a validação do telefone no Cliente. Pode ser alterado para que a mascará permita qualquer quantidade de números, porém a validação só será feita no Servidor após o submit. Outra solução é exibir um alerta caso o valor digitado não seja o esperado, avisando o usuário que deve digitar novamente.

**Comment by expalmer** [comment]
Essa lib [AQUI](https://igorescobar.github.io/jQuery-Mask-Plugin/), não apaga o valor.
A validação dos campos estão sendo feitos pelo backend, então creio que o valor não deve ser apagado, pois caso você tenha esquecido de apenas 1 número, não deveria apagar tudo.
Que acha ?
