### ISSUE TITLE
Cadasrar semestre: gerando erro

### ISSUE THREAD

**Issue by faelborba** [Ulbra-Gravatai/sistemaTCC#91]
### Descrição
Ao tentar cadastrar um semestre é apreentado erro mesm digitando dados corretos
### Comportamento Esperado
ao digitar os dados corretos e clicar em cadastrar ele deveria cadastrar
### Comportamento Atual
após preencher o form e clicar em cadastrar é apresentado erro, independente se o formato estivar correto ou não.
### Passos para reprodução do Problema
acesse a página de cadastrar semestre clique preencha os campos corretamente e clique em salvar e continuar
### Não esqueça de colocar um print com o problema
https://www.dropbox.com/s/g371am5puownfe2/Captura%20de%20tela%20de%202016-11-03%2000-17-53.png?dl=0

**Comment by everton08** [comment]
@faelborba estou dando uma olhada nisso agora! obrigado pelo feedback

**Comment by ThiagoMMoura** [comment]
Corrigido!
![cadastrar semestre ok](https://cloud.githubusercontent.com/assets/8551632/20215220/efd38794-a7f9-11e6-8433-61ac39cba1d9.png)
