### ISSUE TITLE
Falta de Padrão no Layout das Listagens

### ISSUE THREAD

**Issue by ericquadros** [Ulbra-Gravatai/sistemaTCC#93]
### Descrição
Falta um padrão ainda nas listagens, de aluno e professor

### Comportamento Esperado
O esperado é que as listagens sigam um mesmo padrão, observando que é um sistema único e que deveria ser padronizado, por exempo: Listagem de Professor tem uma coluna para o botão editar e outra para o botão remover, ambos são de tamanho normal. Já na listagem de aluno, temos uma coluna para os dois botões e eles são pequenos (xs).

### Comportamento Atual
O comportamento atual é que a listagem de Professor tem uma coluna para o botão editar e outra para o botão remover, ambos são de tamanho normal. Já na listagem de aluno, temos uma coluna para os dois botões e eles são pequenos (xs).

### Passos para reprodução do Problema
Alterar a listagem de Professor, para que tenha uma coluna única com os botões, deixar eles menores (xs) ou alterar a listagem de Aluno, para que os botões fiquem em duas colunas, no tamanho normal...

Listagem do professor com as duas colunas e botões no tamanho normal
![professor-listar](https://cloud.githubusercontent.com/assets/11640701/20001954/889ac022-a265-11e6-836d-ae86fb69f129.png)

Listagem do aluno com uma coluna e os botões no tamanho menor
![aluno-listar](https://cloud.githubusercontent.com/assets/11640701/20001987/b16564ee-a265-11e6-99f4-6a62ddd0091b.png)

**Comment by ThiagoMMoura** [comment]
Isso já foi corrigido.
