### ISSUE TITLE
Erro ao cadastrar semestre

### ISSUE THREAD

**Issue by beped** [Ulbra-Gravatai/sistemaTCC#94]
### Descrição
Mensagem de erro ao tentar cadastrar semestre
### Comportamento Esperado
Após preencher os dados corretamente e clicar em "Salvar e continuar", deveria cadastrar o semestre.
### Comportamento Atual
Quando clica no botão "Salvar e continuar" ao invés de cadastrar o semestre aparece uma mensagem de erro.
### Passos para reprodução do Problema
Entrar em "Cadastrar Semestre", preencher os dados e clicar em "Salvar e continuar"
![erro1](https://cloud.githubusercontent.com/assets/11295620/20003730/34b23c88-a26f-11e6-8b3d-49f12450fc78.jpg)

**Comment by everton08** [comment]
@beped estou dando uma olhada nesse exato momento o cadastro do semestre na parte do back-end, em seguida já irei subir tudo com a correção da issue #95 !!! Obrigado pelo feedback

**Comment by ThiagoMMoura** [comment]
Corrigido!
![cadastrar semestre ok](https://cloud.githubusercontent.com/assets/8551632/20215246/1cd60974-a7fa-11e6-8bcf-5c42f2b75d77.png)
