### ISSUE TITLE
Falta de padrão ao criar semestre ( campo "Campus" )

### ISSUE THREAD

**Issue by beped** [Ulbra-Gravatai/sistemaTCC#95]
### Descrição
O campo "Campus" está como texto no "Cadastrar Semestre", podendo assim haver problemas mais para frente, podendo existir Campus idênticos com nomes diferentes. Ex: Gravataí != Gravatai !=Grvatai ( erro de digitação, por exemplo), etc. Uma filtragem de TCC's pegando como filtro o Campus seria uma dor de cabeça

### Comportamento Esperado
Caixa de seleção com valores pré-estabelecidos. Ex: Gravataí, Canoas, São Jerônimo.

### Comportamento Atual
Campo de texto para digitar nome da cidade.

### Passos para reprodução do Problema
Basta clicar em Cadastrar Semestre e já aparecerá.

![erro2](https://cloud.githubusercontent.com/assets/11295620/20003967/8d0a087e-a270-11e6-976f-94b445c872ec.jpg)

**Comment by everton08** [comment]
@beped já alterei isso e irei subir em breve para a branch master! obrigado pelo feedback

**Comment by ThiagoMMoura** [comment]
Agora o campo é uma combo box, corrigindo assim o problema
![campus ok](https://cloud.githubusercontent.com/assets/8551632/20215327/88fb2a6c-a7fa-11e6-8f0a-de104b5d7d55.png)
